version: '2'
services:
  nginx:
    image: nginxhustlesa
    ports:
      - "18080:80"
      - "18443:443"
    depends_on:
      - hustlesa
#    volumes:
#      - /var/log/nginx:/var/log/nginx
#      - /home/ilyaufo/hustlesa/html/:/etc/nginx/html/
  db:
    image: postgres:9.5
    env_file: postgres.env
#    volumes:
#      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
  hustlesa:
    image: hustlesa
    env_file: prod.env
    depends_on:
      - db
